id: 136
user: eq19
span: span-117
title: eQuantum
baseurl: /syntax
repository: VirtualNetworks/syntax
action: VirtualNetworks/parser/actions/runs/15078327112
description: We develop an Integrated Scripts under The eQuantum Project

#debug:
#  dist: false
#  compress: true
#  shortcodes: true

lsi: false
incremental: true
highlighter: rouge
plugins_dir: _plugins

gist:
  noscript: false

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  with_frontmatter: true

exclude:
  - LICENSE
  - vendor/
  - action.yml  
  - Dockerfile

plugins:
  - jemoji
  - jekyll-gist
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-relative-links
  - jekyll-github-metadata
  - jekyll-titles-from-headings
  - jekyll-optional-front-matter

track:
  spin: [10, 5]
  pinned: [maps, feed, lexer, parser, syntax, grammar, boulder, imdisk, liquid, jib, cerbot, raphael]
  organization: [Chetabahana, FeedMapping, GlobalZones, HybridModels, JunctionTerms, KernelPatterns, MappingSystem, NeuralSystem, ObjectModules, VirtualNetworks, WeakNegative, WeakPositive, ZeroWeak]
